
const brendsLogoImage = [
        {
            name: "barbour",
            url: "./images/brands/barbour.png"
        },
        {
            name: "kate_spade",
            url: "./images/brands/kate_spade.png"
        },
        {
            name: "lvmh",
            url: "./images/brands/lvmh.png"
        },
        {
            name: "estee_lauder",
            url: "./images/brands/estee_lauder.png"
        },
        {
            name: "tjx",
            url: "./images/brands/tjx.png"
        },
        {
            name: "river_island",
            url: "./images/brands/river_island.png"
        },
        {
            name: "radisson",
            url: "./images/brands/radisson.png"
        },
        {
            name: "g-starraw",
            url: "./images/brands/g-starraw.png"
}];//данные про партнеров

const statisticItem = [
    {
        data: '140%',
        subscription: "Qubit's top customers annual growth rate."
    },
    {
        data: '$20bn',
        subscription: "Online sales generated by our customers in 2020."
    },
    {
        data: '364',
        subscription: "Ecommerce stores are growing faster with Qubit."
    },
    {
        data: '9.5m',
        subscription: "Personalized experiences delivered every hour."
    },{
        data: '4.4m',
        subscription: "Shoppers influenced by Qubit every day."
    },
    {
        data: '$1.6bn',
        subscription: "Incremental revenue generated by our customers in 2020.*"
}];//статистические данные 

const aiData = [
    {
        name: "More insight",
        url: "./images/ai_icons/insight.svg",
        text: "Learn which products drive performance and which don't, through automated insights you can action."
    },
    {
        name: "More personal",
        url: "./images/ai_icons/personal.svg",
        text: "Qubit CommerceAI generates a model per shopper to make every customer interaction more relevant."
    },
    {
        name: "More effective",
        url: "./images/ai_icons/effective.svg",
        text: "Qubit fuses data, intent, and design tools to enable your team to create more effective customer experiences."
}];//данные в аи блок

const doData = [
    {
        name: "1:1 Product recommendations",
        url: "./images/do_icons/recomendation.svg",
        text: "Use deep learning recommendations to engage customers in seconds."
    },
    {
        name: "1:1 Product badging",
        url: "./images/do_icons/badging.svg",
        text: "Guide discovery with personalized product badging. Push sales with social proofing."
    },
    {
        name: "Personalized content",
        url: "./images/do_icons/personalised.svg",
        text: "Your customers are unique. Present them with content that shows you know them."
    },
    {
        name: "Product insights",
        url: "./images/do_icons/insights.svg",
        text: "A platform packed with insights helping you discover the hard hitting things you can do next."
    },
    {
        name: "CommerceAI",
        url: "./images/do_icons/commerce.svg",
        text: "Your customer's behavioral data is telling you a story. Use predictive and affinity based algorithms to serve them better."
    },
    {
        name: "Platform integrations",
        url: "./images/do_icons/integration.svg",
        text: "Connect Qubit to any tool via API. Import data or trigger an experience on any platform."
}];//данные в ду блок

const sliderData = [
    {
    logo: "./images/slider_img/clinique_logo.svg",
    logoAlt: "clinique_logo",
    url: "./images/slider_img/clinique.jpg",
    imgAlt: "clinique_img",
    text: "Clinique builds relationships with millions of customers each year."
},
{
    logo: "./images/slider_img/river_logo.svg",
    logoAlt: "river_logo",
    url: "./images/slider_img/river_island.jpg",
    imgAlt: "river_img",
    text: "River Island transforms the customer experience with personalization."
},
{
    logo: "./images/slider_img/mandm_logo.svg",
    logoAlt: "mandm_logo",
    url: "./images/slider_img/mandm.jpg",
    imgAlt: "mandm_img",
    text: "MandM Direct drives increase in revenue with deep learning recs."
},
{
    logo: "./images/slider_img/clinique_logo.svg",
    logoAlt: "clinique_logo",
    url: "./images/slider_img/clinique.jpg",
    imgAlt: "clinique_img",
    text: "Clinique builds relationships with millions of customers each year."
},
{
    logo: "./images/slider_img/river_logo.svg",
    logoAlt: "river_logo",
    url: "./images/slider_img/river_island.jpg",
    imgAlt: "river_img",
    text: "River Island transforms the customer experience with personalization."
},
{
    logo: "./images/slider_img/mandm_logo.svg",
    logoAlt: "mandm_logo",
    url: "./images/slider_img/mandm.jpg",
    imgAlt: "mandm_img",
    text: "MandM Direct drives increase in revenue with deep learning recs."
},
{
    logo: "./images/slider_img/clinique_logo.svg",
    logoAlt: "clinique_logo",
    url: "./images/slider_img/clinique.jpg",
    imgAlt: "clinique_img",
    text: "Clinique builds relationships with millions of customers each year."
},
{
    logo: "./images/slider_img/river_logo.svg",
    logoAlt: "river_logo",
    url: "./images/slider_img/river_island.jpg",
    imgAlt: "river_img",
    text: "River Island transforms the customer experience with personalization."
},
{
    logo: "./images/slider_img/mandm_logo.svg",
    logoAlt: "mandm_logo",
    url: "./images/slider_img/mandm.jpg",
    imgAlt: "mandm_img",
    text: "MandM Direct drives increase in revenue with deep learning recs."
},
{
    logo: "./images/slider_img/clinique_logo.svg",
    logoAlt: "clinique_logo",
    url: "./images/slider_img/clinique.jpg",
    imgAlt: "clinique_img",
    text: "Clinique builds relationships with millions of customers each year."
},
{
    logo: "./images/slider_img/river_logo.svg",
    logoAlt: "river_logo",
    url: "./images/slider_img/river_island.jpg",
    imgAlt: "river_img",
    text: "River Island transforms the customer experience with personalization."
},
{
    logo: "./images/slider_img/mandm_logo.svg",
    logoAlt: "mandm_logo",
    url: "./images/slider_img/mandm.jpg",
    imgAlt: "mandm_img",
    text: "MandM Direct drives increase in revenue with deep learning recs."
}];//данные для карточек в слайдер

const industryData = [
    {
        logo: "./images/you_industry_icons/beauty.svg",
        logoAlt: "beauty_logo",
        title: "Beauty and cosmetics",
        text: "Discover relevant products. Push samples. Upsell and replenish.",
        linkText: "Explore our solutions for beauty and cosmetics.",
        linkUrl: "#"
    }, 
    {
        logo: "./images/you_industry_icons/fashion.svg",
        logoAlt: "fashion_logo",
        title: "Fashion",
        text: "Supercharge merchandising. Reach your best customers.",
        linkText: "Explore our solutions for fashion.",
        linkUrl: "#"
    },
    {
        logo: "./images/you_industry_icons/luxury.svg",
        logoAlt: "luxury_logo",
        title: "Luxury",
        text: "Drive brand experience online. Look after your VIPs.",
        linkText: "Explore our solutions for luxury.",
        linkUrl: "#"
    },
    {
        logo: "./images/you_industry_icons/airlines.svg",
        logoAlt: "airlines_logo",
        title: "Airlines",
        text: "Increase loyalty. Boost ancillary sales. Capture every opportunity.",
        linkText: "Explore our solutions for airlines.",
        linkUrl: "#"
    },
    {
        logo: "./images/you_industry_icons/travel.svg",
        logoAlt: "travel_logo",
        title: "Travel & tourism",
        text: "Be persuasive. Inspire travellers. Drive revenue.",
        linkText: "Explore our solutions for travel and tourism.",
        linkUrl: "#"
    },
    {
        logo: "./images/you_industry_icons/betting.svg",
        logoAlt: "betting_logo",
        title: "Online betting",
        text: "Bring events to life. Personalize in real time. Be responsible.",
        linkText: "Explore our solutions for online betting.",
        linkUrl: "#"
}];//данные в индастри блок

function addBrandLogo() {
    brendsLogoImage.forEach(element => {
        const brandsLogo = document.querySelector('.brands_logo');
        const img = document.createElement('img');
    
        img.className = "brends_logo_item";
        img.alt = element.name;
        img.src = element.url;

        brandsLogo.append(img);
    });
}//подгружает логотипы партнеров
addBrandLogo();

function addStatistic() {
    statisticItem.forEach(element => {
        const statisticsWraper = document.querySelector('.statistics_wraper');
        const div = document.createElement('div');

        div.className = 'statistics_item';
        div.innerHTML = `<span class="item_data">${element.data}</span>
                        <p class="item_subscription">${element.subscription}</p>`;
        statisticsWraper.append(div);
    });
}//подгружает статистику на сайт
addStatistic();

function addCards(selector, arr) {
    arr.forEach(element => {
        const BlockCards = document.querySelector(selector);
        const div = document.createElement('div');
    
        div.className = "card_item";
        div.innerHTML = `<img src='${element.url}' alt='${element.name}'>
                                <h3>${element.name}</h3>
                                <p>${element.text}</p>`;
        BlockCards.append(div);
    });
}//подгружает карточки в зависимости от входящих масивов

addCards('.ai_block_cards', aiData);//карточки в аи блок
addCards('.do_block_cards', doData);//карточки в ду блок

function addSlide(selector, arr) {
    const aiBlockCards = document.querySelector(selector);

    arr.forEach(element => {
        const div = document.createElement('div');

        div.className = "slide_item";
        div.innerHTML = `<img src='${element.url}' alt='${element.imgAlt}' class="slide_img">
                        <img src='${element.logo}' alt='${element.logoAlt}'  class="slide_logo">
                                <p>${element.text}</p>`;
        aiBlockCards.append(div);
    });//формирование карточек из масива

    let offset = 0; //переменная для хранения смещения от левого края
    
    document.querySelector('.prev_slide').addEventListener('click', function () {
        offset = offset + 300;
        if (offset > 1750) {
            offset = -1600;
        }
        aiBlockCards.style.left = offset + "px";
    });// предидущий слайд
    document.querySelector('.next_slide').addEventListener('click', function () {
        offset = offset - 300;
        if (offset < -1750) {
            offset = 1600;
        }
        aiBlockCards.style.left = offset + "px";
    });// следующий слайд
}//функция для формирование карточек в слайдер и функционал 
addSlide('.slider', sliderData);

function addIndustryCards() {
    industryData.forEach(element => {
        const BlockCards = document.querySelector('.industry_cards');
        const div = document.createElement('div');

        div.className = "industry_card_item";
        div.innerHTML = `<img src='${element.logo}' alt='${element.logoAlt}'>
                                <h3>${element.title}</h3>
                                <p>${element.text}</p>
                                <a href='${element.linkUrl}'>${element.linkText}</a>`;
        BlockCards.append(div);
    });
}//подгружает карточки в индастриал юлок
addIndustryCards();

function burgerMenu() {
    const burger = document.querySelector('.menu_burger');

    burger.addEventListener('click', function () {
        // console.log("burger");
        const div = document.createElement('div');
        div.className = "burger_modal";
        div.innerHTML = `
        <div class="burger_main_menu">
                <ul class="burger_main_menu_list">
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">Why Qubit?</a>
                    </li>
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">Products</a>
                    </li>
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">Solutions</a>
                    </li>
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">Customers</a>
                    </li>
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">Case studies</a>
                    </li>
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">Resources</a>
                    </li>
                    <li class="burger_list_item">
                        <a href="#" class="burger_menu_link">More</a>
                    </li>
                </ul>
            </div>
            <div class="burger_side_menu">
                <ul class="burger_side_menu_list">
                    <li class="burger_list_item">
                        <button class="default_btn">Book a demo</button>
                    </li>
                    <li class="burger_list_item">
                        <a href="#">Log In</a>
                    </li>
                </ul>
            </div>
        `;

        burger.append(div);
    });
}
burgerMenu();